'use strict';

const ExcelJS = require('exceljs');
const PDFDocument = require('pdfkit');
const path = require('path');
const fs = require('fs');

const { labelForField } = require('./attendanceLabels');

const REPORT_TITLES = {
  employee: 'Employee Attendance Report',
  department: 'Department Attendance Report',
  organization: 'Organization Attendance Report',
  summary: 'Attendance Summary Report',
  overtime: 'Overtime Report',
  late: 'Late Arrival Report',
  absenteeism: 'Absenteeism Report',
  regularization: 'Regularization Report',
  payroll: 'Payroll Attendance Report',
};

function formatDate(d) {
  const dt = d instanceof Date ? d : new Date(d);
  if (Number.isNaN(dt.getTime())) return String(d);
  return dt.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
}

function resolveLogoPath(logoUrl) {
  if (!logoUrl) return null;
  if (logoUrl.startsWith('http')) return null;
  const clean = logoUrl.replace(/^\/+/, '');
  const full = path.resolve(process.cwd(), clean);
  return fs.existsSync(full) ? full : null;
}

function pdfHeader(doc, branding, title, generatedBy) {
  const logo = resolveLogoPath(branding.logoUrl);
  if (logo) {
    try {
      doc.image(logo, 40, 40, { width: 48, height: 48 });
    } catch {
      /* ignore bad image */
    }
  }
  doc.fontSize(14).text(branding.companyName || 'Organization', logo ? 100 : 40, 42);
  if (branding.address) doc.fontSize(9).text(branding.address, logo ? 100 : 40, 62, { width: 400 });
  if (branding.contactDetails) doc.fontSize(9).text(branding.contactDetails, logo ? 100 : 40, 78, { width: 400 });
  doc.moveDown(2);
  doc.fontSize(12).text(title, { align: 'center' });
  doc.fontSize(9).text(`Generated: ${formatDate(new Date())}`, { align: 'center' });
  if (generatedBy) doc.text(`Generated by: ${generatedBy}`, { align: 'center' });
  doc.moveDown();
}

async function buildExcel(branding, reportType, rows, filtersSummary) {
  const wb = new ExcelJS.Workbook();
  const ws = wb.addWorksheet('Report', { views: [{ state: 'frozen', ySplit: 5 }] });
  const title = REPORT_TITLES[reportType] || 'Attendance Report';

  ws.mergeCells('A1:H1');
  ws.getCell('A1').value = `${branding.companyName || 'Organization'} — ${title}`;
  ws.getCell('A1').font = { size: 14, bold: true };
  ws.mergeCells('A2:H2');
  ws.getCell('A2').value = branding.address || '';
  ws.mergeCells('A3:H3');
  ws.getCell('A3').value = `Generated: ${formatDate(new Date())} | Filters: ${filtersSummary}`;
  ws.getRow(4).values = [];

  if (!rows.length) {
    ws.getCell('A5').value = 'No data for selected filters';
    return wb;
  }

  const headers = Object.keys(rows[0]);
  const headerRow = ws.getRow(5);
  headers.forEach((h, i) => {
    const c = headerRow.getCell(i + 1);
    c.value = labelForField(h);
    c.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0F766E' } };
  });

  rows.forEach((r, idx) => {
    const row = ws.getRow(6 + idx);
    headers.forEach((h, i) => {
      row.getCell(i + 1).value = r[h];
    });
  });

  ws.columns.forEach((col) => {
    let max = 12;
    col.eachCell({ includeEmpty: false }, (cell) => {
      const len = String(cell.value || '').length;
      if (len > max) max = Math.min(len + 2, 40);
    });
    col.width = max;
  });

  return wb;
}

function buildPdf(branding, reportType, rows, filtersSummary, generatedBy) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40, size: 'A4' });
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const title = REPORT_TITLES[reportType] || 'Attendance Report';
    pdfHeader(doc, branding, title, generatedBy);
    doc.fontSize(8).text(`Filters: ${filtersSummary}`, { align: 'left' });
    doc.moveDown();

    if (!rows.length) {
      doc.text('No data for selected filters.');
      doc.end();
      return;
    }

    const headers = Object.keys(rows[0]);
    const colWidth = (doc.page.width - 80) / Math.min(headers.length, 6);
    let y = doc.y;
    doc.fontSize(8).font('Helvetica-Bold');
    headers.slice(0, 8).forEach((h, i) => {
      doc.text(labelForField(h), 40 + i * colWidth, y, { width: colWidth, ellipsis: true });
    });
    y += 14;
    doc.font('Helvetica');

    rows.slice(0, 500).forEach((row) => {
      if (y > doc.page.height - 60) {
        doc.addPage();
        pdfHeader(doc, branding, title, generatedBy);
        y = doc.y;
      }
      headers.slice(0, 8).forEach((h, i) => {
        doc.text(String(row[h] ?? ''), 40 + i * colWidth, y, { width: colWidth, ellipsis: true });
      });
      y += 12;
    });

    const range = doc.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i += 1) {
      doc.switchToPage(i);
      doc.fontSize(8).text(
        `Page ${i + 1} of ${range.count}`,
        40,
        doc.page.height - 30,
        { align: 'center', width: doc.page.width - 80 },
      );
    }

    doc.end();
  });
}

module.exports = {
  REPORT_TITLES,
  buildExcel,
  buildPdf,
};
