'use strict';

/**
 * Monthly late-arrival & early-exit report — aggregated per department and emailed to
 * the concerned department (its manager, with an HR fallback). Run from the monthly cron.
 */

const { sendMail } = require('../../../utils/mail');
const logger = require('../../../utils/logger');

const MONTHS = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];

const HR_FALLBACK_EMAIL = (process.env.HR_ADMIN_EMAIL || '').trim();

/** Per employee, late & early-exit tallies for the given month, grouped by department. */
async function getMonthlyLateEarlyRows(pool, year, month) {
  const { rows } = await pool.query(
    `SELECT COALESCE(NULLIF(TRIM(e.department), ''), 'Unassigned') AS department,
            e.emp_id, e.full_name,
            COUNT(*) FILTER (WHERE a.is_late = true OR a.status = 'Late')::int          AS late_days,
            COALESCE(SUM(a.late_minutes) FILTER (WHERE a.is_late = true OR a.status = 'Late'), 0)::int AS late_minutes,
            COUNT(*) FILTER (WHERE a.early_departure = true)::int                       AS early_days,
            COALESCE(SUM(a.early_departure_minutes) FILTER (WHERE a.early_departure = true), 0)::int  AS early_minutes
     FROM attendance a
     JOIN employees e ON e.id = a.employee_id AND e.deleted_at IS NULL
     WHERE EXTRACT(YEAR FROM a.date) = $1
       AND EXTRACT(MONTH FROM a.date) = $2
       AND (a.is_late = true OR a.status = 'Late' OR a.early_departure = true)
     GROUP BY 1, e.emp_id, e.full_name
     ORDER BY 1, e.full_name ASC`,
    [year, month],
  );
  return rows;
}

/** department name -> manager work email (for routing the report). */
async function getDepartmentManagerEmails(pool) {
  const { rows } = await pool.query(
    `SELECT d.name AS department, me.work_email AS manager_email
     FROM departments d
     LEFT JOIN employees me ON me.id = d.manager_id AND me.deleted_at IS NULL
     WHERE d.is_active = true`,
  );
  const map = new Map();
  for (const r of rows) {
    if (r.manager_email && String(r.manager_email).includes('@')) {
      map.set(String(r.department).trim().toLowerCase(), String(r.manager_email).trim());
    }
  }
  return map;
}

function minutesLabel(m) {
  const mins = Number(m) || 0;
  if (mins < 60) return `${mins} min`;
  const h = Math.floor(mins / 60);
  const r = mins % 60;
  return r ? `${h}h ${r}m` : `${h}h`;
}

function buildHtml(department, periodLabel, rows) {
  const lateTotal = rows.reduce((s, r) => s + (r.late_days || 0), 0);
  const earlyTotal = rows.reduce((s, r) => s + (r.early_days || 0), 0);
  const body = rows.map((r) => `
    <tr>
      <td style="padding:6px 8px;border-bottom:1px solid #eef2f7;">${r.full_name} <span style="color:#94a3b8;">(${r.emp_id || '—'})</span></td>
      <td style="padding:6px 8px;border-bottom:1px solid #eef2f7;text-align:center;">${r.late_days || 0}</td>
      <td style="padding:6px 8px;border-bottom:1px solid #eef2f7;text-align:center;color:#64748b;">${minutesLabel(r.late_minutes)}</td>
      <td style="padding:6px 8px;border-bottom:1px solid #eef2f7;text-align:center;">${r.early_days || 0}</td>
      <td style="padding:6px 8px;border-bottom:1px solid #eef2f7;text-align:center;color:#64748b;">${minutesLabel(r.early_minutes)}</td>
    </tr>`).join('');

  return `
  <div style="font-family:Arial,sans-serif;max-width:680px;border:1px solid #e2e8f0;border-radius:8px;padding:22px;">
    <h2 style="margin:0 0 4px;color:#0f766e;">Late Arrival &amp; Early Exit Report</h2>
    <p style="margin:0 0 16px;color:#475569;font-size:14px;">
      Department: <strong>${department}</strong> &nbsp;·&nbsp; Period: <strong>${periodLabel}</strong>
    </p>
    <p style="margin:0 0 16px;color:#475569;font-size:13px;">
      ${rows.length} employee(s) · ${lateTotal} late instance(s) · ${earlyTotal} early-exit instance(s)
    </p>
    <table style="width:100%;border-collapse:collapse;font-size:13px;">
      <thead>
        <tr style="background:#f1f5f9;">
          <th style="padding:8px;text-align:left;">Employee</th>
          <th style="padding:8px;">Late Days</th>
          <th style="padding:8px;">Late Time</th>
          <th style="padding:8px;">Early Exits</th>
          <th style="padding:8px;">Early Time</th>
        </tr>
      </thead>
      <tbody>${body}</tbody>
    </table>
    <p style="margin:18px 0 0;color:#94a3b8;font-size:12px;">Automated monthly report generated by the HRIS attendance module.</p>
  </div>`;
}

/**
 * Build and email the previous-month late/early report to each department.
 * Idempotent per (year, month, department) via attendance_monthly_report_log.
 */
async function emailMonthlyReports(pool, tenantDb, year, month) {
  const rows = await getMonthlyLateEarlyRows(pool, year, month);
  if (!rows.length) {
    return { departments: 0, emailsSent: 0, skipped: 0 };
  }

  const mgrEmails = await getDepartmentManagerEmails(pool);
  const periodLabel = `${MONTHS[month - 1]} ${year}`;

  // Group rows by department.
  const byDept = new Map();
  for (const r of rows) {
    if (!byDept.has(r.department)) byDept.set(r.department, []);
    byDept.get(r.department).push(r);
  }

  let emailsSent = 0;
  let skipped = 0;

  for (const [department, deptRows] of byDept) {
    // Already sent for this period+department? Skip (idempotent).
    const { rows: existing } = await pool.query(
      `SELECT 1 FROM attendance_monthly_report_log
       WHERE report_year = $1 AND report_month = $2 AND department = $3`,
      [year, month, department],
    );
    if (existing.length) { skipped += 1; continue; }

    const recipients = [];
    const mgr = mgrEmails.get(String(department).trim().toLowerCase());
    if (mgr) recipients.push(mgr);
    if (HR_FALLBACK_EMAIL && HR_FALLBACK_EMAIL.includes('@') && !recipients.includes(HR_FALLBACK_EMAIL)) {
      recipients.push(HR_FALLBACK_EMAIL);
    }

    const lateCount = deptRows.reduce((s, r) => s + (r.late_days || 0), 0);
    const earlyCount = deptRows.reduce((s, r) => s + (r.early_days || 0), 0);

    if (!recipients.length) {
      logger.warn(`[attendanceMonthlyReport] tenant=${tenantDb} dept="${department}" ${periodLabel}: no recipient (no dept manager / HR fallback)`);
      // Still log it so we don't recompute endlessly; record with empty recipients.
      await pool.query(
        `INSERT INTO attendance_monthly_report_log (report_year, report_month, department, recipients, late_count, early_count)
         VALUES ($1,$2,$3,$4,$5,$6) ON CONFLICT DO NOTHING`,
        [year, month, department, '', lateCount, earlyCount],
      );
      skipped += 1;
      continue;
    }

    // Write the idempotency row FIRST inside a transaction, then send the email.
    // If the email send fails we roll back the row so the next cron run retries.
    // This prevents the inverse race where email succeeds but the DB write crashes,
    // causing a duplicate send on the next run.
    const client = await pool.connect();
    try {
      await client.query('BEGIN');
      await client.query(
        `INSERT INTO attendance_monthly_report_log (report_year, report_month, department, recipients, late_count, early_count)
         VALUES ($1,$2,$3,$4,$5,$6) ON CONFLICT DO NOTHING`,
        [year, month, department, recipients.join(', '), lateCount, earlyCount],
      );

      await sendMail({
        to: recipients.join(', '),
        subject: `Late Arrival & Early Exit Report — ${department} — ${periodLabel}`,
        html: buildHtml(department, periodLabel, deptRows),
      });

      await client.query('COMMIT');
      emailsSent += 1;
      logger.info(`[attendanceMonthlyReport] sent tenant=${tenantDb} dept="${department}" ${periodLabel} to ${recipients.join(', ')}`);
    } catch (e) {
      try { await client.query('ROLLBACK'); } catch (_) {}
      logger.error(`[attendanceMonthlyReport] send failed tenant=${tenantDb} dept="${department}" ${periodLabel}`, e);
    } finally {
      client.release();
    }
  }

  return { departments: byDept.size, emailsSent, skipped };
}

module.exports = {
  getMonthlyLateEarlyRows,
  getDepartmentManagerEmails,
  emailMonthlyReports,
};
