'use strict';

const NOTIFICATION_TYPES = {
  ONBOARDING_HANDOVER: 'ONBOARDING_HANDOVER',
  OFFER_REJECTED: 'OFFER_REJECTED',
  DOCUMENT_APPROVED: 'DOCUMENT_APPROVED',
  DOCUMENT_REJECTED: 'DOCUMENT_REJECTED',
  DOCUMENT_REMINDER: 'DOCUMENT_REMINDER',
  ONBOARDING_STEP_COMPLETED: 'ONBOARDING_STEP_COMPLETED',
  OFFER_ACCEPTED: 'OFFER_ACCEPTED',
  SIGNED_OFFER_UPLOADED: 'SIGNED_OFFER_UPLOADED',
};

module.exports = {
  NOTIFICATION_TYPES,
};
